#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: globalserver_globalserver zoneserver_zoneserver barrackserver_barrackserver

globalserver_globalserver: 
	$(MAKE) -C GlobalServer all -f GlobalServer.cbp.mak

zoneserver_zoneserver: 
	$(MAKE) -C ZoneServer all -f ZoneServer.cbp.mak

barrackserver_barrackserver: 
	$(MAKE) -C BarrackServer all -f BarrackServer.cbp.mak

clean: clean_globalserver_globalserver clean_zoneserver_zoneserver clean_barrackserver_barrackserver

clean_globalserver_globalserver: 
	$(MAKE) -C GlobalServer clean -f GlobalServer.cbp.mak

clean_zoneserver_zoneserver: 
	$(MAKE) -C ZoneServer clean -f ZoneServer.cbp.mak

clean_barrackserver_barrackserver: 
	$(MAKE) -C BarrackServer clean -f BarrackServer.cbp.mak

.PHONY: clean_globalserver_globalserver clean_zoneserver_zoneserver clean_barrackserver_barrackserver

