/**
 *
 *   ██████╗   ██╗ ███████╗ ███╗   ███╗ ██╗   ██╗
 *   ██╔══██╗ ███║ ██╔════╝ ████╗ ████║ ██║   ██║
 *   ██████╔╝ ╚██║ █████╗   ██╔████╔██║ ██║   ██║
 *   ██╔══██╗  ██║ ██╔══╝   ██║╚██╔╝██║ ██║   ██║
 *   ██║  ██║  ██║ ███████╗ ██║ ╚═╝ ██║ ╚██████╔╝
 *   ╚═╝  ╚═╝  ╚═╝ ╚══════╝ ╚═╝     ╚═╝  ╚═════╝
 *
 * @license <license placeholder>
 */


// ---------- Includes ------------
#include "PacketType.h"


// ------ Structure declaration -------

const PacketTypeInfo packetTypeInfo = {
    #define REGISTER_PACKET_TYPE_ENTRY(packetType, packetValue, packetSize) \
        .packets[packetType] = {.value = packetValue, .size = packetSize, .string = STRINGIFY (packetType)}

	/** ===================================================================== */
	/** ======================== Barrack -> Client  ========================= */
	/** ===================================================================== */

	/** ========== Account ========== */
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (BC_ACCOUNT_PROP, 0x004D, 0),
	/** Description : Change the family name */
	REGISTER_PACKET_TYPE_ENTRY (BC_BARRACKNAME_CHANGE, 0x0017, 75),
	/** Description : Login and logout the account */
	REGISTER_PACKET_TYPE_ENTRY (BC_LOGINOK, 0x000D, 37),
	REGISTER_PACKET_TYPE_ENTRY (BC_LOGOUTOK, 0x000E, 6),

	/** ========== Commander ========== */
	/** Description : Create a new commander */
	REGISTER_PACKET_TYPE_ENTRY (BC_COMMANDER_CREATE, 0x0010, 318),
	/** Description : Delete one or all commanders of the barrack */
	REGISTER_PACKET_TYPE_ENTRY (BC_COMMANDER_DESTROY, 0x0011, 7),
	/** Description : List all the existing commanders */
	REGISTER_PACKET_TYPE_ENTRY (BC_COMMANDER_LIST, 0x000F, 0),
	/** Description : Makes the commander jump */
	REGISTER_PACKET_TYPE_ENTRY (BC_JUMP, 0x0056, 19),

	/** ========== IES ========== */
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (BC_IES_MODIFY_INFO, 0x0047, 0),
	REGISTER_PACKET_TYPE_ENTRY (BC_IES_MODIFY_LIST, 0x0048, 0),
	REGISTER_PACKET_TYPE_ENTRY (BC_IES_REVISION_DELETE, 0x004A, 0),

	/** ========== Chat ========== */
	/** Description : Communicate in the barrack */
	REGISTER_PACKET_TYPE_ENTRY (BC_CHAT, 0x0053, 0),

	/** ========== Server ========== */
	/** Description : Describes an entry of a social server */
	REGISTER_PACKET_TYPE_ENTRY (BC_SERVER_ENTRY, 0x0057, 18),
	/** Description : Describes the information needed for a single map instance */
	REGISTER_PACKET_TYPE_ENTRY (BC_SINGLE_INFO, 0x0013, 337),
	/** Description : Start the loading screen */
	REGISTER_PACKET_TYPE_ENTRY (BC_START_GAMEOK, 0x0012, 60),

	/** ========== UNKNOWN ========== */
	REGISTER_PACKET_TYPE_ENTRY (BC_NORMAL, 0x004F, 0),
	REGISTER_PACKET_TYPE_ENTRY (BC_ECHO, 0x0015, 26),
	REGISTER_PACKET_TYPE_ENTRY (BC_MYPAGE_MAP, 0x0016, 0),
	REGISTER_PACKET_TYPE_ENTRY (BC_MESSAGE, 0x0014, 0),


	/** ===================================================================== */
	/** ========================== Client -> Game =========================== */
	/** ===================================================================== */

	/** ========== Status ========== */
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (BG_ALIVE_PING, 0x0389, 8),

	/** ========== Commander ========== */
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (BG_COMMANDER_DESTROY, 0x038B, 83),
	REGISTER_PACKET_TYPE_ENTRY (BG_BAN_COMMANDER, 0x038D, 14),

	/** ========== Zone ========== */
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (BG_CREATE_ZONE, 0x0393, 8),
	REGISTER_PACKET_TYPE_ENTRY (BG_ENTER_ZONE, 0x038A, 196),

	/** ========== IES ========== */
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (BG_IES_HIS_DEL, 0x0391, 0),
	REGISTER_PACKET_TYPE_ENTRY (BG_IES_MODIFY_INFO, 0x038F, 0),

	/** ========== UNKNOWN ========== */
	REGISTER_PACKET_TYPE_ENTRY (BG_NORMAL, 0x0398, 0),
	REGISTER_PACKET_TYPE_ENTRY (BG_START, 0x0385, 8),


	/** ===================================================================== */
	/** ========================= Client -> Barrack ========================= */
	/** ===================================================================== */

	/** ========== Account ========== */
	/** Description : Request a login by login / password */
	REGISTER_PACKET_TYPE_ENTRY (CB_LOGIN, 0x0003, 53),
	/** Description : Request a login by a nexon passport */
	REGISTER_PACKET_TYPE_ENTRY (CB_LOGIN_BY_PASSPORT, 0x0004, 531),
	/** Description : Request a logout */
	REGISTER_PACKET_TYPE_ENTRY (CB_LOGOUT, 0x0005, 10),
	/** Description : Request the information about the barrack */
	REGISTER_PACKET_TYPE_ENTRY (CB_START_BARRACK, 0x0006, 11),
	/** Description : Request a family name change */
	REGISTER_PACKET_TYPE_ENTRY (CB_BARRACKNAME_CHANGE, 0x000A, 74),
	/** Description : Sends information about the current barrack */
	REGISTER_PACKET_TYPE_ENTRY (CB_CURRENT_BARRACK, 0x004E, 39),
	/** Description : Request to buy a new barrack */
	REGISTER_PACKET_TYPE_ENTRY (CB_BUY_THEMA, 0x004C, 18),

	/** ========== Commander ========== */
	/** Description : Requests to create, destroy, move, jump or pose a commander */
	REGISTER_PACKET_TYPE_ENTRY (CB_COMMANDER_CREATE, 0x0007, 91),
	REGISTER_PACKET_TYPE_ENTRY (CB_COMMANDER_DESTROY, 0x0008, 11),
	REGISTER_PACKET_TYPE_ENTRY (CB_COMMANDER_MOVE, 0x000B, 31),
	REGISTER_PACKET_TYPE_ENTRY (CB_JUMP, 0x0055, 19),
	REGISTER_PACKET_TYPE_ENTRY (CB_POSE, 0x0050, 15),
	/** Description : Request to delete a pet */
	REGISTER_PACKET_TYPE_ENTRY (CB_DELETE_PET, 0x0059, 18),
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (CB_PET_PC, 0x0058, 26),

	/** ========== Server ========== */
	/** Description : Sends when the button is pressed, requests the loading screen */
	REGISTER_PACKET_TYPE_ENTRY (CB_START_GAME, 0x0009, 13),

	/** ========== IES ========== */
	/** Description : UNKNOWN */
	REGISTER_PACKET_TYPE_ENTRY (CB_IES_MODIFY_INFO, 0x0046, 0),
	REGISTER_PACKET_TYPE_ENTRY (CB_IES_REVISION_DELETE, 0x0049, 0),

	/** ========== Visit ========== */
	/** Description : Visits someone else's barrack */
	REGISTER_PACKET_TYPE_ENTRY (CB_VISIT, 0x004B, 74),

	/** ========== UNKNOWN ========== */
	REGISTER_PACKET_TYPE_ENTRY (CB_ECHO, 0x000C, 30),
	REGISTER_PACKET_TYPE_ENTRY (CB_ECHO_NORMAL, 0x0054, 0),
	REGISTER_PACKET_TYPE_ENTRY (CB_PLACE_CMD, 0x0051, 46),
	REGISTER_PACKET_TYPE_ENTRY (CB_CHAT, 0x0052, 0),

	/** ===================================================================== */
	/** ========================= Client -> Social ========================== */
	/** ===================================================================== */

	/** ========== Server ========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_LOGIN, 0x0B55, 48),
	REGISTER_PACKET_TYPE_ENTRY (CS_NORMAL_GAME_START, 0x0B6C, 6),

	/** ========== Chat ========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_CHAT, 0x0B60, 0),
	REGISTER_PACKET_TYPE_ENTRY (CS_CHAT_HISTORY, 0x0B64, 22),
	REGISTER_PACKET_TYPE_ENTRY (CS_CHAT_READ, 0x0B65, 30),

	/** ========== GroupChat ========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_CREATE_GROUP_CHAT, 0x0B61, 6),
	REGISTER_PACKET_TYPE_ENTRY (CS_GROUP_CHAT_INVITE, 0x0B62, 78),
	REGISTER_PACKET_TYPE_ENTRY (CS_REFRESH_GROUP_CHAT, 0x0B63, 6),
	REGISTER_PACKET_TYPE_ENTRY (CS_REMOVE_GROUP_MEMBER, 0x0B66, 14),

	/** ========== Friend  ========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_FRIEND_CMD, 0x0B5E, 24),
	REGISTER_PACKET_TYPE_ENTRY (CS_FRIEND_SET_ADDINFO, 0x0B5F, 160),
	REGISTER_PACKET_TYPE_ENTRY (CS_REQ_ADD_FRIEND, 0x0B5C, 70),
	REGISTER_PACKET_TYPE_ENTRY (CS_REQ_BLOCK_FRIEND, 0x0B5D, 70),

	/** ========== Market ========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_REQ_MARKET_LIST, 0x0B5A, 158),
	REGISTER_PACKET_TYPE_ENTRY (CS_REQ_MY_SELL_LIST, 0x0B5B, 10),

	/** ========== PC ==========	 */
	REGISTER_PACKET_TYPE_ENTRY (CS_PC_INTERACTION, 0x0B67, 24),
	REGISTER_PACKET_TYPE_ENTRY (CS_PC_INTERACTION_HISTORY, 0x0B69, 32),
	REGISTER_PACKET_TYPE_ENTRY (CS_REQ_RELATED_PC_SESSION, 0x0B68, 16),
	REGISTER_PACKET_TYPE_ENTRY (CS_REDIS_SKILLPOINT, 0x0B6A, 22),

	/** ========== Party ========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_PARTY_CLIENT_INFO_SEND, 0x0B6B, 0),

	/** ========== PVP ========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_REQUEST_PVP_RANKING, 0x0B6E, 83),
	REGISTER_PACKET_TYPE_ENTRY (CS_PVP_COMMAND, 0x0B6D, 18),

	/** =========== SNS =========== */
	REGISTER_PACKET_TYPE_ENTRY (CS_REGISTER_SNS_ID, 0x0B58, 16),
	REGISTER_PACKET_TYPE_ENTRY (CS_REQ_SNS_PC_INFO, 0x0B59, 0),


	/** ===================================================================== */
	/** ========================== Client -> Zone =========================== */
	/** ===================================================================== */

	/** =========== Party =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_ACCEPT_PARTY_QUEST, 0x0D8B, 20),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQUEST_SOME_PARTY, 0x0D84, 34),

	/** =========== Barrack =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_VISIT_BARRACK, 0x0D4B, 74),

	/** =========== Equipment =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_ACHIEVE_EQUIP, 0x0CB6, 18),

	/** =========== Skills =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_ACTIVE_ABILITY, 0x0C35, 15),
	REGISTER_PACKET_TYPE_ENTRY (CZ_BUFF_REMOVE, 0x0BE7, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CANCEL_TRANSFORM_SKILL, 0x0D1B, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CAST_CONTROL_SHOT, 0x0CDC, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_CANCEL, 0x0C16, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_CANCEL_SCRIPT, 0x0CB1, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_CELL_LIST, 0x0D5A, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_GROUND, 0x0C14, 56),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_JUMP_REQ, 0x0C0B, 30),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_SELF, 0x0C15, 35),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_TARGET, 0x0C12, 19),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_TARGET_ANI, 0x0C13, 23),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_TOOL_GROUND_POS, 0x0D5B, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SKILL_USE_HEIGHT, 0x0D8A, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_HARDCODED_SKILL, 0x0D15, 34),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SPC_SKILL_POS, 0x0D4C, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SUMMON_COMMAND, 0x0D6D, 18),

	/** =========== UI =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_ADD_HELP, 0x0D55, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CLICK_TRIGGER, 0x0C07, 15),
	REGISTER_PACKET_TYPE_ENTRY (CZ_UI_EVENT, 0x0C50, 0),

	/** =========== Economy =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_ADD_SELLMODE_ITEM, 0x0D32, 30),
	REGISTER_PACKET_TYPE_ENTRY (CZ_DELETE_SELLMODE_ITEM, 0x0D33, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_BUY_PROPERTYSHOP_ITEM, 0x0D89, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_COMMON_SHOP_LIST, 0x0C78, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXCHANGE_ACCEPT, 0x0C67, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXCHANGE_AGREE, 0x0C6D, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXCHANGE_CANCEL, 0x0C71, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXCHANGE_DECLINE, 0x0C68, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXCHANGE_FINALAGREE, 0x0C6F, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXCHANGE_OFFER, 0x0C6B, 30),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXCHANGE_REQUEST, 0x0C64, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ON_ITEMBUY_MODE, 0x0D39, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ON_SELLITEM_MODE, 0x0D34, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_OPEN_AUTOSELLER, 0x0D80, 20),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REGISTER_AUTOSELLER, 0x0D7F, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SOLD_ITEM, 0x0CDA, 19),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_MARKET_BUY, 0x0D79, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_MARKET_REGISTER, 0x0D78, 27),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_CANCEL_MARKET_ITEM, 0x0D7C, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_NPC_AUCTION_CMD, 0x0D67, 30),

	/** =========== Server =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_BACKTO_ORIGINAL_SERVER, 0x0C8F, 12),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CONNECT, 0x0BB9, 54),
	REGISTER_PACKET_TYPE_ENTRY (CZ_COMPLETE_PRELOAD, 0x0D53, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_GAME_READY, 0x0BFD, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_LOGOUT, 0x0BFF, 10),

	/** =========== Channel =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CHANGE_CHANNEL, 0x0D87, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_CHANNEL_TRAFFICS, 0x0D88, 12),

	/** =========== Configs =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CHANGE_CONFIG, 0x0CB8, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CHANGE_CONFIG_STR, 0x0CB9, 34),

	/** =========== Commander =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CHANGE_HEAD, 0x0D4E, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_HEAD_ROTATE, 0x0C19, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_JUMP, 0x0C0A, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_POSE, 0x0C1B, 34),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REST_SIT, 0x0C0E, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_RESURRECT, 0x0BFA, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_VEHICLE_RIDE, 0x0D6E, 15),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ROTATE, 0x0C18, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_CHANGEJOB, 0x0D4D, 14),

	/** =========== Battle =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CLIENT_ATTACK, 0x0CDF, 15),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CLIENT_DAMAGE, 0x0CDE, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CLIENT_HIT_LIST, 0x0D3E, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_COUNTER_ATTACK, 0x0D1E, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_DYNAMIC_CASTING_END, 0x0CB0, 19),
	REGISTER_PACKET_TYPE_ENTRY (CZ_DYNAMIC_CASTING_START, 0x0CAF, 23),
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXP_UP_BY_MONSTER, 0x0C3A, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_GUARD, 0x0C9F, 19),

	/** =========== Crafting  =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CREATE_ARROW_CRAFT, 0x0D4F, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_PUZZLE_CRAFT, 0x0D81, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_RECIPE, 0x0C84, 0),

	/** =========== Chat =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CHAT, 0x0C1C, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CHAT_LOG, 0x0C1D, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CHAT_MACRO, 0x0CC2, 146),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SHOUT, 0x0C1E, 0),

	/** =========== Commands =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CUSTOM_COMMAND, 0x0CC0, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_CUSTOM_SCP, 0x0D12, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_FORMATION_CMD, 0x0D7E, 24),

	/** =========== Direction =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_DIRECTION_MOVE_STATE, 0x0D5D, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_DIRECTION_PROCESS, 0x0D5C, 18),

	/** =========== Dialog =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_DIALOG_ACK, 0x0C42, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_DIALOG_SELECT, 0x0C43, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_DIALOG_STRINGINPUT, 0x0C44, 138),
	REGISTER_PACKET_TYPE_ENTRY (CZ_DIALOG_TX, 0x0C83, 0),

	/** =========== Wiki =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_GET_WIKI_REWARD, 0x0CF0, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_WIKI_CATEGORY_RANK_PAGE_INFO, 0x0D6F, 78),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_WIKI_PROP_RANK, 0x0CEF, 16),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_WIKI_RANK, 0x0CEC, 15),
	REGISTER_PACKET_TYPE_ENTRY (CZ_WIKI_GET, 0x0C93, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_WIKI_RECIPE_UPDATE, 0x0C94, 10),

	/** =========== HackShield =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_HACKSHIELD_BUFFER, 0x0D8F, 612),

	/** =========== Item =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_GIVEITEM_TO_DUMMYPC, 0x0CA9, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_HARDCODED_ITEM, 0x0D1A, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_BUY, 0x0C24, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_DELETE, 0x0C20, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_DROP, 0x0C1F, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_DROP_TO_OBJECT, 0x0D26, 26),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_EQUIP, 0x0C26, 19),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_SELL, 0x0C25, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_UNEQUIP, 0x0C27, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_USE, 0x0C21, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_USE_TO_GROUND, 0x0C23, 30),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ITEM_USE_TO_ITEM, 0x0C22, 306),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_ITEM_GET, 0x0C9D, 1),

	/** =========== IES =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_IES_MODIFY_INFO, 0x0CD3, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_IES_REVISION_DELETE, 0x0CD6, 0),

	/** =========== Keyboard =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_KEYBOARD_BEAT, 0x0D43, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_KEYBOARD_MOVE, 0x0C08, 41),

	/** =========== Party =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_PARTY_INVITE_ACCEPT, 0x0D75, 75),
	REGISTER_PACKET_TYPE_ENTRY (CZ_PARTY_INVITE_CANCEL, 0x0D76, 75),
	REGISTER_PACKET_TYPE_ENTRY (CZ_PARTY_PROP_CHANGE, 0x0D77, 17),

	/** =========== Map =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_GET_MAP_REVEAL_ACHIEVE, 0x0CD2, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MAP_REVEAL_INFO, 0x0CCA, 146),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MAP_SEARCH_INFO, 0x0CCB, 55),

	/** =========== Page =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_GET_TARGET_GUESTPAGE, 0x0D31, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_GUESTPAGE_COMMENT_ADD, 0x0D2D, 278),
	REGISTER_PACKET_TYPE_ENTRY (CZ_GET_TARGET_MYPAGE, 0x0D2E, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MYPAGE_COMMENT_ADD, 0x0D2B, 278),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MYPAGE_COMMENT_DELETE, 0x0D2C, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ON_MYPAGE_MODE, 0x0D2F, 14),

	/** =========== Movements =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_EXPECTED_STOP_POS, 0x0C09, 31),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MOVEMENT_INFO, 0x0C11, 23),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MOVE_BARRACK, 0x0C00, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MOVE_PATH, 0x0C0C, 27),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MOVE_PATH_END, 0x0D41, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MOVE_STOP, 0x0C0D, 35),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MOVE_ZONE_OK, 0x0BBC, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ON_AIR, 0x0C0F, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_ON_GROUND, 0x0C10, 10),

	/** =========== Object =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CONTROL_OBJECT_ROTATE, 0x0D6C, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_OBJECT_MOVE, 0x0D6B, 27),
	REGISTER_PACKET_TYPE_ENTRY (CZ_OBJ_RECORD_POS, 0x0D7D, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_S_OBJ_VALUE_C, 0x0C8A, 24),

	/** =========== Quickslot =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_QUICKSLOT_LIST, 0x0CC6, 0),

	/** =========== Quests =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_G_QUEST_CHECK, 0x0D28, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_QUEST_CHECK_SAVE, 0x0CE2, 50),
	REGISTER_PACKET_TYPE_ENTRY (CZ_QUEST_NPC_STATE_CHECK, 0x0CD0, 14),

	/** =========== Spray =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_SPRAY_DRAW_INFO, 0x0CE4, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SPRAY_REQ_INFO, 0x0CE3, 14),

	/** =========== MGame =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_MGAME_JOIN_CMD, 0x0D54, 46),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_MGAME_CHAT, 0x0D73, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_MGAME_VIEW, 0x0D72, 18),

	/** =========== Social =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_RESET_SOCIAL_MODE, 0x0D30, 10),

	/** =========== Pet =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_PET_EQUIP, 0x0D82, 30),

	/** =========== UNKNOWN & MISC =========== */
	REGISTER_PACKET_TYPE_ENTRY (CZ_CLIENT_DIRECT, 0x0D1F, 30),
	REGISTER_PACKET_TYPE_ENTRY (CZ_FLEE_OBSTACLE, 0x0CF9, 26),
	REGISTER_PACKET_TYPE_ENTRY (CZ_HELP_READ_TYPE, 0x0D40, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_HOLD, 0x0C17, 11),
	REGISTER_PACKET_TYPE_ENTRY (CZ_INTE_WARP, 0x0BE8, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_JUNGTAN_TOGGLE, 0x0C37, 16),
	REGISTER_PACKET_TYPE_ENTRY (CZ_LOG, 0x0D0A, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_MOVEHIT_SCP, 0x0D44, 22),
	REGISTER_PACKET_TYPE_ENTRY (CZ_PING, 0x0D8C, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_PROPERTY_COMPARE, 0x0D61, 15),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_ACHIEVE_RANK_PAGE_INFO, 0x0D70, 78),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_CABINET_LIST, 0x0D7A, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_GET_CABINET_ITEM, 0x0D7B, 20),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_DUMMYPC_INFO, 0x0D4A, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_MINITEXT, 0x0D50, 266),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_NORMAL_TX, 0x0C8B, 29),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_NORMAL_TX_NUMARG, 0x0C90, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REQ_TX_ITEM, 0x0CF1, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REVEAL_NPC_STATE, 0x0D86, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_REWARD_CMD, 0x0D60, 14),
	REGISTER_PACKET_TYPE_ENTRY (CZ_RUN_BGEVENT, 0x0D23, 74),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SAVE_INFO, 0x0CA6, 0),
	REGISTER_PACKET_TYPE_ENTRY (CZ_STOP_ALLPC, 0x0D52, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_STOP_TIMEACTION, 0x0D49, 10),
	REGISTER_PACKET_TYPE_ENTRY (CZ_SWAP_INVITEM, 0x0C28, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_TOURNAMENT_GIFT, 0x0D74, 18),
	REGISTER_PACKET_TYPE_ENTRY (CZ_WAREHOUSE_CMD, 0x0CDB, 27),


	/** ===================================================================== */
	/** ========================== Zone -> Client =========================== */
	/** ===================================================================== */

	/** =========== Skills =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_ABILITY_LIST, 0x0C34, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ACHIEVE_POINT, 0x0CB5, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ACHIEVE_POINT_LIST, 0x0CB4, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ACTIVE_ABILITY, 0x0C36, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ADD_SKILL_EFFECT, 0x0D24, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_BUFF_ADD, 0x0BE3, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_BUFF_CLEAR, 0x0BE6, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_BUFF_LIST, 0x0BE2, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_BUFF_REMOVE, 0x0BE5, 12),
	REGISTER_PACKET_TYPE_ENTRY (ZC_BUFF_UPDATE, 0x0BE4, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CAST_TARGET, 0x0D0D, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_COOLDOWN_CHANGED, 0x0C75, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_COOLDOWN_LIST, 0x0C74, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_COOLDOWN_RATE, 0x0CC8, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILLMAP_LIST, 0x0CA8, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_ADD, 0x0C33, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_CAST, 0x0BD9, 38),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_CAST_CANCEL, 0x0BD8, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_DISABLE, 0x0BDB, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_FORCE_GROUND, 0x0BE0, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_FORCE_TARGET, 0x0BDF, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_HIT_INFO, 0x0BE1, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ORDER_SKILL_JUMP, 0x0BCE, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_JUMP, 0x0BCF, 38),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_LIST, 0x0C32, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_MELEE_GROUND, 0x0BDE, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_MELEE_TARGET, 0x0BDD, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_RANGE_CIRCLE, 0x0D07, 28),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_RANGE_DBG, 0x0D04, 58),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_RANGE_FAN, 0x0D05, 40),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_RANGE_SQUARE, 0x0D06, 40),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_READY, 0x0BDA, 46),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SKILL_USE_CANCEL, 0x0BDC, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_HEAL_INFO, 0x0BF4, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_HARDCODED_SKILL, 0x0D14, 26),


	/** =========== Equipment =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_ACHIEVE_EQUIP, 0x0CB7, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHANGE_EQUIP_DURABILITY, 0x0C82, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EQUIP_ITEM_REMOVE, 0x0CD8, 18),

	/** =========== PKS =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_ACTION_PKS, 0x0D19, 35),

	/** =========== Addon =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_ADDON_MSG, 0x0C4F, 0),

	/** =========== Actor =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_ADD_HP, 0x0BD7, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ADD_STAMINA, 0x0CA2, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_BORN, 0x0CB3, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CANCEL_DEADEVENT, 0x0D18, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ENTER_DUMMYPC, 0x0BC0, 292),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ENTER_PC, 0x0BBE, 316),
	REGISTER_PACKET_TYPE_ENTRY (ZC_FLY, 0x0CFF, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_FLY_MATH, 0x0D00, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_GUARD, 0x0CA0, 19),
	/** -- Set the position of the actor-- */
	REGISTER_PACKET_TYPE_ENTRY (ZC_SET_POS, 0x0BD0, 22),
	/** --  */
	REGISTER_PACKET_TYPE_ENTRY (ZC_HEAD_ROTATE, 0x0BEB, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_STANCE_CHANGE, 0x0BD6, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ROTATE, 0x0BE9, 19),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ROTATE_RESERVED, 0x0BEA, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_QUICK_ROTATE, 0x0BED, 18),

	/** =========== Monster =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_MONSTER_DIST, 0x0CF3, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MONSTER_LIFETIME, 0x0CE7, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MONSTER_PROPERTY, 0x0CFD, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MONSTER_SDR_CHANGED, 0x0C98, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MON_STAMINA, 0x0D11, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATED_MONSTERAPPEARANCE, 0x0BD3, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ENTER_MONSTER, 0x0BBF, 0),

	/** =========== Commander =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_COMMANDER_LOADER_INFO, 0x0C8C, 0),
	/** -- Dead -- */
	REGISTER_PACKET_TYPE_ENTRY (ZC_DEAD, 0x0BEF, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESURRECT, 0x0BF0, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESURRECT_DIALOG, 0x0BF2, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESURRECT_HERE_ACK, 0x0BFC, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESURRECT_SAVE_POINT_ACK, 0x0BFB, 7),
	/** -- Exp -- */
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXP_UP, 0x0C38, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXP_UP_BY_MONSTER, 0x0C39, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_GIVE_EXP_TO_PC, 0x0CBD, 42),
	REGISTER_PACKET_TYPE_ENTRY (ZC_JOB_EXP_UP, 0x0D0F, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MAX_EXP_CHANGED, 0x0C3D, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PC_LEVELUP, 0x0C3B, 11),
	/** -- */
	REGISTER_PACKET_TYPE_ENTRY (ZC_JOB_PTS, 0x0D10, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PC, 0x0D09, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PC_ATKSTATE, 0x0D3F, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PC_PROP_UPDATE, 0x0CDD, 9),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PC_STAT_AVG, 0x0C3C, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATED_DUMMYPC, 0x0BC1, 250),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATED_PCAPPEARANCE, 0x0BD2, 250),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATE_ALL_STATUS, 0x0C5F, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATE_MHP, 0x0C41, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATE_MSHIELD, 0x0D02, 12),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATE_SHIELD, 0x0D01, 12),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UPDATE_SP, 0x0C3F, 15),
	/** -- Pose */
	REGISTER_PACKET_TYPE_ENTRY (ZC_REST_SIT, 0x0BCB, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_POSE, 0x0BEE, 34),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MYPC_ENTER, 0x0CA4, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_STAMINA, 0x0CA1, 10),

	/** =========== NPC =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_NPC_STATE_LIST, 0x0CCF, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SET_NPC_STATE, 0x0CCE, 18),

	/** =========== Attach / Detach =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_ATTACH_BY_KNOCKBACK, 0x0D6A, 38),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ATTACH_TO_OBJ, 0x0D56, 48),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DETACH_FROM_OBJ, 0x0D57, 14),

	/** =========== Server relation =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_BACKTO_ORIGINAL_SERVER, 0x0C8E, 8),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CONNECT_FAILED, 0x0BBD, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CONNECT_OK, 0x0BBA, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LOGOUT_OK, 0x0C02, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_START_GAME, 0x0C05, 26),
	REGISTER_PACKET_TYPE_ENTRY (ZC_START_INFO, 0x0D0E, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TIME_FACTOR, 0x0C7A, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LOGIN_TIME, 0x0CBC, 14),

	/** =========== Battle =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_CAUTION_DAMAGE_INFO, 0x0BF6, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CAUTION_DAMAGE_RELEASE, 0x0BF7, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_HIT_INFO, 0x0BF3, 60),

	/** =========== Log =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_BEGIN_KILL_LOG, 0x0D64, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_END_KILL_LOG, 0x0D65, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CLEAR_KILL_LOG, 0x0D66, 6),

	/** =========== Animation =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHANGE_ANI, 0x0C56, 44),
	REGISTER_PACKET_TYPE_ENTRY (ZC_STD_ANIM, 0x0C59, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_FIX_ANIM, 0x0C57, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_ANIM, 0x0C58, 12),
	REGISTER_PACKET_TYPE_ENTRY (ZC_BGMODEL_ANIM_INFO, 0x0D69, 15),

	/** =========== Camera =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHANGE_CAMERA, 0x0C97, 31),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHANGE_CAMERA_ZOOM, 0x0C9A, 34),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESET_VIEW, 0x0C04, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_VIEW_FOCUS, 0x0D13, 24),

	/** =========== Relation =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHANGE_RELATION, 0x0BF1, 11),

	/** =========== Collision damage =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_COLL_DAMAGE, 0x0D42, 11),

	/** =========== Economy =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_COMMON_SHOP_LIST, 0x0C79, 8),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_AGREE_ACK, 0x0C6E, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_CANCEL_ACK, 0x0C72, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_DECLINE_ACK, 0x0C69, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_FINALAGREE_ACK, 0x0C70, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_OFFER_ACK, 0x0C6C, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_REQUEST_ACK, 0x0C65, 72),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_REQUEST_RECEIVED, 0x0C66, 71),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_START, 0x0C6A, 71),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXCHANGE_SUCCESS, 0x0C73, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SOLD_ITEM_LIST, 0x0CD9, 0),

	/** =========== UI =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_CREATE_LAYERBOX, 0x0CAB, 38),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CREATE_SCROLLLOCKBOX, 0x0CAD, 38),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CUSTOM_DIALOG, 0x0C85, 47),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_CLOSE, 0x0C4A, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_COMMON_TRADE, 0x0C4C, 39),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_ITEM_SELECT, 0x0C49, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_NEXT, 0x0C47, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_NUMBERRANGE, 0x0C4D, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_OK, 0x0C46, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_SELECT, 0x0C48, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_STRINGINPUT, 0x0C4E, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIALOG_TRADE, 0x0C4B, 39),
	REGISTER_PACKET_TYPE_ENTRY (ZC_REMOVE_SCROLLLOCKBOX, 0x0CAE, 10),

	/** =========== Chat =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHAT, 0x0BD4, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHAT_MACRO_LIST, 0x0CC3, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHAT_WITH_TEXTCODE, 0x0BD5, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EMOTICON, 0x0CF5, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SHOUT, 0x0C62, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SHOUT_FAILED, 0x0C63, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SHOW_EMOTICON, 0x0CF6, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SYSTEM_MSG, 0x0CE0, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_WORLD_MSG, 0x0CBA, 43),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SHARED_MSG, 0x0CEE, 10),

	/** =========== Items =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_ENTER_ITEM, 0x0BC2, 103),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ENABLE_SHOW_ITEM_GET, 0x0CBB, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_ADD, 0x0C2D, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_DROPABLE, 0x0D25, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_EQUIP_LIST, 0x0C2C, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_GET, 0x0C9E, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_INVENTORY_INDEX_LIST, 0x0C2B, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_INVENTORY_LIST, 0x0C2A, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_REMOVE, 0x0C2E, 20),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_USE, 0x0C2F, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ITEM_USE_TO_GROUND, 0x0C30, 22),

	/** =========== IES =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_IES_MODIFY_INFO, 0x0CD4, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_IES_MODIFY_LIST, 0x0CD5, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_IES_REVISION_DELETE, 0x0CD7, 0),

	/** =========== Party =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_FOUND_PARTY_LIST, 0x0D83, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PARTY_CHAT, 0x0C80, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PARTY_DESTROY, 0x0C7D, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PARTY_ENTER, 0x0C7B, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PARTY_INFO, 0x0C7E, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PARTY_INST_INFO, 0x0C81, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PARTY_LIST, 0x0C7F, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PARTY_OUT, 0x0C7C, 24),

	/** =========== Movements =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_COUNTER_MOVE, 0x0D1D, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXPECTED_STOPPOS, 0x0BC7, 35),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_BARRACK, 0x0C01, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_DIR, 0x0BC6, 40),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_IGNORE_COLLISION, 0x0C99, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_PATH, 0x0BC4, 42),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_PATH_MATH, 0x0D2A, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_POS, 0x0BC5, 42),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_SPEED, 0x0BC9, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_STOP, 0x0BCA, 23),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_ZONE, 0x0BBB, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_ZONE_OK, 0x0BFE, 85),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PC_MOVE_STOP, 0x0D51, 35),
	REGISTER_PACKET_TYPE_ENTRY (ZC_JUMP, 0x0BCC, 19),
	REGISTER_PACKET_TYPE_ENTRY (ZC_JUMP_DIR, 0x0BCD, 34),
	REGISTER_PACKET_TYPE_ENTRY (ZC_FORCE_MOVE, 0x0D16, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_HOLD_MOVE_PATH, 0x0CFA, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOTIONBLUR, 0x0D0B, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_WARP_MOVE, 0x0D29, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RUN_FROM, 0x0D58, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_FSM_MOVE, 0x0CE1, 0),

	/** =========== Single zone =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_MOVE_SINGLE_ZONE, 0x0C8D, 18),

	/** =========== Quickslot =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_QUICK_SLOT_LIST, 0x0C31, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_QUICKSLOT_REGISTER, 0x0CC5, 46),

	/** =========== Play events =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_ALARMSOUND, 0x0C5B, 83),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_ANI, 0x0C55, 24),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_EXP_TEXT, 0x0C5D, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_FORCE, 0x0D0C, 78),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_MUSICQUEUE, 0x0C53, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_NAVI_EFFECT, 0x0C5E, 150),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_SKILL_ANI, 0x0C9B, 82),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_SKILL_CAST_ANI, 0x0C9C, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PLAY_SOUND, 0x0C51, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZC_STOP_ALARMSOUND, 0x0C5C, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_STOP_MUSICQUEUE, 0x0C54, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_STOP_SOUND, 0x0C52, 14),

	/** =========== UI =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_UI_INFO_LIST, 0x0CCC, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_UI_OPEN, 0x0C95, 39),

	/** =========== Spray =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_SPRAY_DRAW_INFO, 0x0CE6, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SPRAY_ID, 0x0CE5, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SPRAY_LIKE_LIST, 0x0CE8, 0),

	/** =========== Help =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_HELP_ADD, 0x0D3D, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_HELP_LIST, 0x0D3C, 0),

	/** =========== Layer =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_LAYER_INFO, 0x0CC1, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LAYER_PC_LIST, 0x0CBE, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LAYER_PC_SOBJ_PROP, 0x0CBF, 0),

	/** =========== Map =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_MAP_REVEAL_LIST, 0x0CC9, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SHOW_MAP, 0x0CF8, 0),

	/** =========== Hackshield =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_HACKSHIELD_BUFFER, 0x0D8E, 608),

	/** =========== Page =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_MYPAGE_MAP, 0x0D35, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_GUESTPAGE_MAP, 0x0D36, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ON_MYPAGE_MODE, 0x0D37, 0),

	/** =========== Knock =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_KNOCKBACK_INFO, 0x0BF8, 66),
	REGISTER_PACKET_TYPE_ENTRY (ZC_KNOCKDOWN_INFO, 0x0BF9, 67),

	/** =========== Session =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_SESSION_OBJECTS, 0x0C86, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SESSION_OBJ_ADD, 0x0C87, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SESSION_OBJ_REMOVE, 0x0C88, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SESSION_OBJ_TIME, 0x0C89, 14),

	/** =========== Sync =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_SYNC_START, 0x0D45, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SYNC_END, 0x0D46, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SYNC_EXEC, 0x0D47, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SYNC_EXEC_BY_SKILL_TIME, 0x0D48, 18),

	/** =========== Gamepad =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_VIBRATE, 0x0D1C, 30),

	/** =========== Wiki =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_WIKI_ADD, 0x0C92, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_WIKI_BOOL_PROP_UPDATE, 0x0CEB, 12),
	REGISTER_PACKET_TYPE_ENTRY (ZC_WIKI_COUNT_UPDATE, 0x0CE9, 19),
	REGISTER_PACKET_TYPE_ENTRY (ZC_WIKI_INT_PROP_UPDATE, 0x0CEA, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZC_WIKI_LIST, 0x0C91, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_WIKI_RANK_LIST, 0x0CED, 0),

	/** =========== Commands =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_EXEC_CLIENT_SCP, 0x0CCD, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_GM_ORDER, 0x0CA3, 10),

	/** =========== UNKNOWN & MISC =========== */
	REGISTER_PACKET_TYPE_ENTRY (ZC_CHECK_INVINDEX, 0x0C29, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DIRECTION_APC, 0x0D68, 20),
	REGISTER_PACKET_TYPE_ENTRY (ZC_DUMP_PROPERTY, 0x0C61, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ENABLE_CONTROL, 0x0C96, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ENTER_HOOK, 0x0CFB, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_FACTION, 0x0D63, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_FILE_MOVE, 0x0BD1, 46),
	REGISTER_PACKET_TYPE_ENTRY (ZC_GD_RANK, 0x0D22, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_GROUND_EFFECT, 0x0CFE, 50),
	REGISTER_PACKET_TYPE_ENTRY (ZC_HSKILL_CONTROL, 0x0D17, 22),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LEAVE, 0x0BC3, 12),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LEAVE_HOOK, 0x0CFC, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LEAVE_TRIGGER, 0x0CB2, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_LOOKAT_OBJ, 0x0D59, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MESSAGE, 0x0C03, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_MSPD, 0x0BC8, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_NORMAL, 0x0D27, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_ON_BUYITEM_MODE, 0x0D3A, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_OPTION_LIST, 0x0CA7, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_OVERHEAT_CHANGED, 0x0C76, 26),
	REGISTER_PACKET_TYPE_ENTRY (ZC_OWNER, 0x0D21, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PING, 0x0D8D, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_PROPERTY_COMPARE, 0x0D62, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_QUIET, 0x0C06, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RANK_ACHIEVE_ADD, 0x0CD1, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESET_BOX, 0x0CAC, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESET_SKILL_FORCEID, 0x0CF4, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESET_SOCIAL_MODE, 0x0D38, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RESTORATION, 0x0C40, 12),
	REGISTER_PACKET_TYPE_ENTRY (ZC_RULLET_LIST, 0x0CC4, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SAVE_INFO, 0x0CA5, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SET_LAYER, 0x0CAA, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SHOW_GROUND_ITEM_MARK, 0x0D3B, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SHOW_MODEL, 0x0D03, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZC_SPC_TRIGGER_EXEC, 0x0D71, 30),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TARGET_ROTATE, 0x0BEC, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TEAMID, 0x0D08, 11),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TEST_AGENT, 0x0C77, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TEST_DBG, 0x0CF2, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TEXT, 0x0C3E, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TO_ALL_CLIENT, 0x0D5E, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TO_CLIENT, 0x0D5F, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TO_SOMEWHERE_CLIENT, 0x0D85, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TREASUREMARK_BY_MAP, 0x0CF7, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TREASUREMARK_LIST_MAP, 0x00B3, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_TRICK_PACKET, 0x0CC7, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZC_CLIENT_DIRECT, 0x0D20, 30),


	/** ===================================================================== */
	/** ============================ Client -> H ============================ */
	/** ===================================================================== */
	REGISTER_PACKET_TYPE_ENTRY (CH_DAEMON_MODIFY, 0x0177, 1065),
	REGISTER_PACKET_TYPE_ENTRY (CH_DELETE_FILE_ITEM, 0x016E, 262),
	REGISTER_PACKET_TYPE_ENTRY (CH_FORCE_STOP_DAEMON, 0x0173, 20),
	REGISTER_PACKET_TYPE_ENTRY (CH_LOGIN, 0x016F, 48),
	REGISTER_PACKET_TYPE_ENTRY (CH_MESSAGE, 0x017A, 272),
	REGISTER_PACKET_TYPE_ENTRY (CH_PROPERTY_TABLE, 0x0161, 14),
	REGISTER_PACKET_TYPE_ENTRY (CH_PROPERTY_TABLE_BLOCK, 0x0163, 14),
	REGISTER_PACKET_TYPE_ENTRY (CH_SET_AUTOMATICALLY_RUNNING, 0x0178, 7),
	REGISTER_PACKET_TYPE_ENTRY (CH_SET_HUB_RUNNING, 0x017B, 7),
	REGISTER_PACKET_TYPE_ENTRY (CH_START_DAEMON, 0x0171, 20),
	REGISTER_PACKET_TYPE_ENTRY (CH_STATE_TABLE, 0x0165, 14),
	REGISTER_PACKET_TYPE_ENTRY (CH_STOP_DAEMON, 0x0172, 20),
	REGISTER_PACKET_TYPE_ENTRY (CH_STOP_DAEMON_TABLE, 0x0168, 14),
	REGISTER_PACKET_TYPE_ENTRY (CH_UPDATE_FILE, 0x0176, 275),
	REGISTER_PACKET_TYPE_ENTRY (CH_UPDATE_SVN, 0x017E, 24),
	REGISTER_PACKET_TYPE_ENTRY (CH_UPLOADED_FILE_TABLE, 0x016B, 14),
	REGISTER_PACKET_TYPE_ENTRY (CH_UPLOAD_FILE, 0x0174, 274),
	REGISTER_PACKET_TYPE_ENTRY (CH_UPLOAD_FILE_BLOCK, 0x0175, 4114),



	/** ===================================================================== */
	/** ========================= Game -> Barrack =========================== */
	/** ===================================================================== */

	REGISTER_PACKET_TYPE_ENTRY (GB_ADD_SERVER_ZONE, 0x0394, 13),
	REGISTER_PACKET_TYPE_ENTRY (GB_BAN_COMMANDER, 0x038E, 14),
	REGISTER_PACKET_TYPE_ENTRY (GB_BAN_LIST, 0x038C, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_CHANNEL_TRAFFIC, 0x0397, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_IES_HIS_DEL, 0x0392, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_IES_MODIFY_INFO, 0x0390, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_NORMAL, 0x0399, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_SEND_ALIVE_SERVERS, 0x0388, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_UPDATE_ALL_WORLD, 0x0396, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_UPDATE_ZONE, 0x0395, 0),
	REGISTER_PACKET_TYPE_ENTRY (GB_ZONE_START, 0x0386, 8),
	REGISTER_PACKET_TYPE_ENTRY (GB_ZONE_STOP, 0x0387, 8),



	/** ===================================================================== */
	/** ========================== Game -> Social =========================== */
	/** ===================================================================== */

	REGISTER_PACKET_TYPE_ENTRY (GS_NORMAL, 0x0A2C, 0),
	REGISTER_PACKET_TYPE_ENTRY (GS_TO_INTEG, 0x0A2E, 0),


	/** ===================================================================== */
	/** ============================ Game -> Zone =========================== */
	/** ===================================================================== */

	REGISTER_PACKET_TYPE_ENTRY (GZ_ADD_SERVER_ZONE, 0x00B9, 13),
	REGISTER_PACKET_TYPE_ENTRY (GZ_ALL_ZONE, 0x00C5, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_APPTIME, 0x00CC, 10),
	REGISTER_PACKET_TYPE_ENTRY (GZ_BAN_COMMANDER, 0x00A9, 18),
	REGISTER_PACKET_TYPE_ENTRY (GZ_BAN_LIST, 0x007A, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_CHANGE_NAME, 0x00C1, 79),
	REGISTER_PACKET_TYPE_ENTRY (GZ_CHANNEL_TRAFFIC, 0x00BF, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_CHAT_STOP, 0x0082, 18),
	REGISTER_PACKET_TYPE_ENTRY (GZ_CHAT_STOP_TIME, 0x0084, 83),
	REGISTER_PACKET_TYPE_ENTRY (GZ_COMMANDER_INFO, 0x007C, 22),
	REGISTER_PACKET_TYPE_ENTRY (GZ_COM_KICK, 0x0079, 79),
	REGISTER_PACKET_TYPE_ENTRY (GZ_CREATE_FIELDBOSS, 0x00A1, 28),
	REGISTER_PACKET_TYPE_ENTRY (GZ_CREATE_ROOM, 0x0098, 23),
	REGISTER_PACKET_TYPE_ENTRY (GZ_CREATE_ZONE, 0x00B7, 19),
	REGISTER_PACKET_TYPE_ENTRY (GZ_DELETE_DAILY_ACHIEVE, 0x00B0, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_DESTROY_COMMANDER, 0x00A8, 26),
	REGISTER_PACKET_TYPE_ENTRY (GZ_DESTROY_ROOM, 0x00A5, 10),
	REGISTER_PACKET_TYPE_ENTRY (GZ_FOUND_PARTYID_LIST, 0x0096, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_GIFTITEM, 0x00B4, 26),
	REGISTER_PACKET_TYPE_ENTRY (GZ_GLOBALSERVER_STATE, 0x008B, 7),
	REGISTER_PACKET_TYPE_ENTRY (GZ_IES_HIS_DEL, 0x00AF, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_IES_MODIFY_INFO, 0x00AD, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_MOVE_ZONE, 0x0068, 32),
	REGISTER_PACKET_TYPE_ENTRY (GZ_MSG, 0x006B, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_NORMAL, 0x00C8, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_PARTY_CHAT, 0x0093, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_PARTY_DESTROY, 0x0090, 15),
	REGISTER_PACKET_TYPE_ENTRY (GZ_PARTY_ENTER, 0x008D, 279),
	REGISTER_PACKET_TYPE_ENTRY (GZ_PARTY_INFO, 0x0091, 23),
	REGISTER_PACKET_TYPE_ENTRY (GZ_PARTY_MEMBERLIST, 0x0095, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_PARTY_OUT, 0x008F, 88),
	REGISTER_PACKET_TYPE_ENTRY (GZ_PC_INFO, 0x007D, 22),
	REGISTER_PACKET_TYPE_ENTRY (GZ_QUIET, 0x0071, 7),
	REGISTER_PACKET_TYPE_ENTRY (GZ_RECALL_ALLIANCE, 0x009C, 29),
	REGISTER_PACKET_TYPE_ENTRY (GZ_RECALL_FAIL_ALLIANCE, 0x009E, 10),
	REGISTER_PACKET_TYPE_ENTRY (GZ_RELOAD_MISSION_MAP, 0x009F, 20),
	REGISTER_PACKET_TYPE_ENTRY (GZ_REQ_CHANNEL_TRAFFIC, 0x00BD, 14),
	REGISTER_PACKET_TYPE_ENTRY (GZ_SCHEDULE_UPDATE, 0x00B2, 10),
	REGISTER_PACKET_TYPE_ENTRY (GZ_SEND_ALIVE_SERVERS, 0x0085, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_SHOUT, 0x006D, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_START, 0x0066, 8),
	REGISTER_PACKET_TYPE_ENTRY (GZ_START_MISSION, 0x0099, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_STOP, 0x0067, 8),
	REGISTER_PACKET_TYPE_ENTRY (GZ_TEXT, 0x0073, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_TO_ALL_CLIENT, 0x00CA, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_TO_CLIENT, 0x00CB, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_TO_PC, 0x00CE, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_UPDATED_NOTICE, 0x0080, 6),
	REGISTER_PACKET_TYPE_ENTRY (GZ_UPDATE_ALLWORLD, 0x00BB, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_UPDATE_ZONE, 0x00BA, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_USER_LIST, 0x0088, 6),
	REGISTER_PACKET_TYPE_ENTRY (GZ_USER_SESSION_INFO, 0x00C9, 22),
	REGISTER_PACKET_TYPE_ENTRY (GZ_VAR, 0x00B6, 0),
	REGISTER_PACKET_TYPE_ENTRY (GZ_W, 0x0075, 18),
	REGISTER_PACKET_TYPE_ENTRY (GZ_WHO, 0x006F, 26),
	REGISTER_PACKET_TYPE_ENTRY (GZ_WORLD_MSG, 0x00AB, 43),
	REGISTER_PACKET_TYPE_ENTRY (GZ_ZTZ, 0x00C3, 0),

	REGISTER_PACKET_TYPE_ENTRY (HC_COMMAND_STATE, 0x015F, 63),
	REGISTER_PACKET_TYPE_ENTRY (HC_LOG, 0x0160, 1034),
	REGISTER_PACKET_TYPE_ENTRY (HC_LOGIN, 0x0170, 16),
	REGISTER_PACKET_TYPE_ENTRY (HC_PROPERTY_TABLE_BLOCK, 0x0164, 4112),
	REGISTER_PACKET_TYPE_ENTRY (HC_PROPERTY_TABLE_DESC, 0x0162, 23),
	REGISTER_PACKET_TYPE_ENTRY (HC_SET_AUTOMATICALLY_RUNNING, 0x0179, 7),
	REGISTER_PACKET_TYPE_ENTRY (HC_SET_HUB_RUNNING, 0x017C, 7),
	REGISTER_PACKET_TYPE_ENTRY (HC_STATE_TABLE_BLOCK, 0x0167, 4112),
	REGISTER_PACKET_TYPE_ENTRY (HC_STATE_TABLE_DESC, 0x0166, 23),
	REGISTER_PACKET_TYPE_ENTRY (HC_STOP_DAEMON_TABLE_BLOCK, 0x016A, 4112),
	REGISTER_PACKET_TYPE_ENTRY (HC_STOP_DAEMON_TABLE_DESC, 0x0169, 17),
	REGISTER_PACKET_TYPE_ENTRY (HC_SYSTEMLOG, 0x017D, 1034),
	REGISTER_PACKET_TYPE_ENTRY (HC_UPDATE_PROPERTY, 0x017F, 1034),
	REGISTER_PACKET_TYPE_ENTRY (HC_UPLOADED_FILE_TABLE_BLOCK, 0x016D, 4112),
	REGISTER_PACKET_TYPE_ENTRY (HC_UPLOADED_FILE_TABLE_DESC, 0x016C, 17),

	REGISTER_PACKET_TYPE_ENTRY (HN_AUTH, 0x01C4, 7),
	REGISTER_PACKET_TYPE_ENTRY (HN_COMMAND_FORCE_STOP_DAEMON, 0x01CA, 16),
	REGISTER_PACKET_TYPE_ENTRY (HN_COMMAND_MESSAGE, 0x01CD, 272),
	REGISTER_PACKET_TYPE_ENTRY (HN_COMMAND_START_DAEMON, 0x01C8, 1040),
	REGISTER_PACKET_TYPE_ENTRY (HN_COMMAND_STOP_DAEMON, 0x01C9, 16),
	REGISTER_PACKET_TYPE_ENTRY (HN_COMMAND_UPDATE_FILE, 0x01CB, 15),
	REGISTER_PACKET_TYPE_ENTRY (HN_COMMAND_UPDATE_SVN, 0x01CC, 20),
	REGISTER_PACKET_TYPE_ENTRY (HN_DAEMON_PROPERTYS, 0x01C5, 0),

	REGISTER_PACKET_TYPE_ENTRY (HU_AUTH, 0x0192, 7),
	REGISTER_PACKET_TYPE_ENTRY (HU_DOWNLOAD_FILE_BLOCK, 0x0197, 4106),
	REGISTER_PACKET_TYPE_ENTRY (HU_DOWNLOAD_FILE_EXPLAIN, 0x0195, 266),

	REGISTER_PACKET_TYPE_ENTRY (IS_NORMAL, 0x0FA4, 0),
	REGISTER_PACKET_TYPE_ENTRY (IS_START, 0x0FA1, 6),
	REGISTER_PACKET_TYPE_ENTRY (IS_TO_CLIENT, 0x0FA6, 0),
	REGISTER_PACKET_TYPE_ENTRY (IS_TO_GLOBAL, 0x0FA7, 0),
	REGISTER_PACKET_TYPE_ENTRY (IS_TO_ZONE, 0x0FA8, 0),

	REGISTER_PACKET_TYPE_ENTRY (NH_AUTH, 0x01C3, 10),
	REGISTER_PACKET_TYPE_ENTRY (NH_COMMAND_STATE, 0x01C7, 63),
	REGISTER_PACKET_TYPE_ENTRY (NH_UPDATE_STATE, 0x01C6, 0),

	REGISTER_PACKET_TYPE_ENTRY (RZ_CONNECT, 0x01F5, 44),
	REGISTER_PACKET_TYPE_ENTRY (RZ_NORMAL, 0x01F6, 0),

	REGISTER_PACKET_TYPE_ENTRY (SC_FROM_INTEGRATE, 0x0B57, 0),
	REGISTER_PACKET_TYPE_ENTRY (SC_NORMAL, 0x0B56, 0),

	REGISTER_PACKET_TYPE_ENTRY (SG_ALIVE_PING, 0x0A2A, 6),
	REGISTER_PACKET_TYPE_ENTRY (SG_FROM_INTEG, 0x0A2D, 0),
	REGISTER_PACKET_TYPE_ENTRY (SG_NORMAL, 0x0A2B, 0),
	REGISTER_PACKET_TYPE_ENTRY (SG_START, 0x0A29, 10),

	REGISTER_PACKET_TYPE_ENTRY (SI_ALIVE_PING, 0x0FA3, 6),
	REGISTER_PACKET_TYPE_ENTRY (SI_FROM_GLOBAL, 0x0FA9, 0),
	REGISTER_PACKET_TYPE_ENTRY (SI_NORMAL, 0x0FA5, 0),
	REGISTER_PACKET_TYPE_ENTRY (SI_START, 0x0FA2, 12),

	REGISTER_PACKET_TYPE_ENTRY (SZ_FROM_INTEG, 0x0AF5, 0),
	REGISTER_PACKET_TYPE_ENTRY (SZ_NORMAL, 0x0AF4, 0),
	REGISTER_PACKET_TYPE_ENTRY (SZ_START, 0x0AF2, 8),

	REGISTER_PACKET_TYPE_ENTRY (UH_AUTH, 0x0191, 14),
	REGISTER_PACKET_TYPE_ENTRY (UH_COMMAND_STATE, 0x0193, 266),
	REGISTER_PACKET_TYPE_ENTRY (UH_DOWNLOAD_FILE_BLOCK, 0x0196, 6),
	REGISTER_PACKET_TYPE_ENTRY (UH_START_DOWNLOAD_FILE, 0x0194, 6),


	REGISTER_PACKET_TYPE_ENTRY (ZG_ALL_CLIENT, 0x00C6, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_ALL_ZONE, 0x00C4, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CHANGE_NAME, 0x00C0, 79),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CHANNEL_TRAFFIC, 0x00BE, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CHAT_STOP, 0x0081, 83),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CHAT_STOP_TIME, 0x0083, 79),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CHECK_DOUBLE_LOGIN, 0x00A7, 26),
	REGISTER_PACKET_TYPE_ENTRY (ZG_COMMANDER_ALIVE_PING, 0x008A, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZG_COMMANDER_INFO, 0x007B, 28),
	REGISTER_PACKET_TYPE_ENTRY (ZG_COM_CALL, 0x0077, 97),
	REGISTER_PACKET_TYPE_ENTRY (ZG_COM_GO, 0x0076, 78),
	REGISTER_PACKET_TYPE_ENTRY (ZG_COM_KICK, 0x0078, 144),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CREATE_FIELDBOSS, 0x00A2, 14),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CREATE_ROOM, 0x0097, 23),
	REGISTER_PACKET_TYPE_ENTRY (ZG_CREATE_ZONE, 0x00B8, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZG_DESTROY_FIELDBOSS, 0x00A3, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZG_DESTROY_MISSION_MAP, 0x009A, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZG_DESTROY_ROOM, 0x00A4, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZG_GIFTITEM, 0x00B3, 26),
	REGISTER_PACKET_TYPE_ENTRY (ZG_GLOBAL_CHEAT_CMD, 0x00B1, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_IES_HIS_DEL, 0x00AE, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_IES_MODIFY_INFO, 0x00AC, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_LOGOUT, 0x0087, 15),
	REGISTER_PACKET_TYPE_ENTRY (ZG_MOVE_ZONE, 0x0069, 38),
	REGISTER_PACKET_TYPE_ENTRY (ZG_NORMAL, 0x00C7, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_PARTY_CHAT, 0x0092, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_PARTY_INVITE_ACCEPT, 0x008C, 279),
	REGISTER_PACKET_TYPE_ENTRY (ZG_PARTY_OUT, 0x008E, 88),
	REGISTER_PACKET_TYPE_ENTRY (ZG_PC_INFO, 0x007E, 28),
	REGISTER_PACKET_TYPE_ENTRY (ZG_QUIET, 0x0070, 7),
	REGISTER_PACKET_TYPE_ENTRY (ZG_RECALL_ALLIANCE, 0x009B, 60),
	REGISTER_PACKET_TYPE_ENTRY (ZG_RECALL_FAIL_ALLIANCE, 0x009D, 10),
	REGISTER_PACKET_TYPE_ENTRY (ZG_REGISTER_SESSION, 0x006A, 188),
	REGISTER_PACKET_TYPE_ENTRY (ZG_RELOAD_MISSION_MAP, 0x00A0, 19),
	REGISTER_PACKET_TYPE_ENTRY (ZG_REQ_CREATE_ZONE, 0x00BC, 8),
	REGISTER_PACKET_TYPE_ENTRY (ZG_SERVER_ALIVE_PING, 0x0086, 8),
	REGISTER_PACKET_TYPE_ENTRY (ZG_SHOUT, 0x006C, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_START, 0x0065, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_TEXT, 0x0072, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_TO_PC, 0x00CD, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_UPDATED_NOTICE, 0x007F, 6),
	REGISTER_PACKET_TYPE_ENTRY (ZG_UPDATE_COMMANDER_STATE, 0x0094, 100),
	REGISTER_PACKET_TYPE_ENTRY (ZG_VAR, 0x00B5, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZG_W, 0x0074, 18),
	REGISTER_PACKET_TYPE_ENTRY (ZG_WHO, 0x006E, 83),
	REGISTER_PACKET_TYPE_ENTRY (ZG_WORLD_MSG, 0x00AA, 43),
	REGISTER_PACKET_TYPE_ENTRY (ZG_ZTZ, 0x00C2, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZR_NORMAL, 0x01F7, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZS_NORMAL, 0x0AF3, 0),
	REGISTER_PACKET_TYPE_ENTRY (ZS_START, 0x0AF1, 8),
	REGISTER_PACKET_TYPE_ENTRY (ZS_TO_INTEG, 0x0AF6, 0)

    #undef REGISTER_PACKET_TYPE_ENTRY
};
